-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 16:53:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema summardb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `summardb` DEFAULT CHARACTER SET utf8 ;
USE `summardb` ;

-- -----------------------------------------------------
-- Table `summardb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summardb`.`User` ;

CREATE TABLE IF NOT EXISTS `summardb`.`User` (
  `user_id` VARCHAR(40) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summardb`.`Summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summardb`.`Summary` ;

CREATE TABLE IF NOT EXISTS `summardb`.`Summary` (
  `summary_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(25) NOT NULL,
  `summary_title` VARCHAR(100) NOT NULL,
  `bf_summary` VARCHAR(5000) NOT NULL,
  `af_summary` VARCHAR(2000) NOT NULL,
  `count` INT NOT NULL,
  `input_type` INT NOT NULL,
  `book_title` VARCHAR(100) NULL,
  `book_author` VARCHAR(100) NULL,
  PRIMARY KEY (`summary_id`),
  INDEX `user_id_IDX2` (`user_id` ASC) VISIBLE,
  INDEX `summary_title_IDX2` (`summary_title` ASC) VISIBLE,
  INDEX `book_title_IDX2` (`book_title` ASC) VISIBLE,
  CONSTRAINT `summary2user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `summardb`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summardb`.`Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summardb`.`Quiz` ;

CREATE TABLE IF NOT EXISTS `summardb`.`Quiz` (
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_type` INT NOT NULL,
  `quiz_content` VARCHAR(1500) NOT NULL,
  `quiz_date` DATE NOT NULL,
  `user_id` VARCHAR(25) NOT NULL,
  `summary_id` INT NOT NULL,
  `book_title` VARCHAR(100) NULL,
  `my_answer` VARCHAR(500) NULL,
  `correct_answer` VARCHAR(500) NOT NULL,
  `correct` BOOLEAN NULL,
  `review_answer` VARCHAR(500) NULL,
  `review_correct` BOOLEAN NULL,
  `review_date` DATE NULL,
  PRIMARY KEY (`quiz_id`),
  INDEX `book_title_IDX3` (`book_title` ASC) VISIBLE,
  INDEX `user_id_IDX3` (`user_id` ASC) VISIBLE,
  INDEX `summary_id_IDX3` (`summary_id` ASC) VISIBLE,
  INDEX `quiz_type_IDX3` (`quiz_type` ASC) VISIBLE,
  CONSTRAINT `quiz2user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `summardb`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `quiz2summary_summary_id`
    FOREIGN KEY (`summary_id`)
    REFERENCES `summardb`.`Summary` (`summary_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `quiz2summary_book_title`
    FOREIGN KEY (`book_title`)
    REFERENCES `summardb`.`Summary` (`book_title`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summardb`.`Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summardb`.`Score` ;

CREATE TABLE IF NOT EXISTS `summardb`.`Score` (
  `score_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(25) NOT NULL,
  `summary_id` INT NOT NULL,
  `score` VARCHAR(20) NOT NULL,
  `review_score` VARCHAR(20) NULL,
  `quiz_type` INT NOT NULL,
  PRIMARY KEY (`score_id`),
  INDEX `user_id_idx5` (`user_id` ASC) VISIBLE,
  INDEX `summary_id_idx5` (`summary_id` ASC) VISIBLE,
  INDEX `quiz_type_idx5` (`quiz_type` ASC) VISIBLE,
  CONSTRAINT `score2user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `summardb`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `score2summary_summary_id`
    FOREIGN KEY (`summary_id`)
    REFERENCES `summardb`.`Summary` (`summary_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `score2quiz_quiz_type`
    FOREIGN KEY (`quiz_type`)
    REFERENCES `summardb`.`Quiz` (`quiz_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
